# Generated by Django 5.1 on 2026-02-24 20:13

import apps.core.models
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('rates', '0001_initial'),
        ('schools', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BetreuerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('anrede', models.CharField(choices=[('herr', 'Herr'), ('frau', 'Frau'), ('divers', 'Divers')], max_length=20)),
                ('geburtsdatum', models.DateField()),
                ('geschlecht', models.CharField(choices=[('maennlich', 'Maennlich'), ('weiblich', 'Weiblich'), ('divers', 'Divers')], max_length=20)),
                ('staatsangehoerigkeit', models.CharField(default='deutsch', max_length=100)),
                ('street', models.CharField(max_length=200)),
                ('house_number', models.CharField(max_length=20)),
                ('plz', models.CharField(max_length=10)),
                ('city', models.CharField(max_length=100)),
                ('kontoinhaber', models.CharField(max_length=200)),
                ('iban', apps.core.models.EncryptedCharField(max_length=255)),
                ('bic', models.CharField(blank=True, default='', max_length=11)),
                ('betreuer_type', models.CharField(choices=[('schueler', 'Schueler/in'), ('sonst_mitarbeiter', 'Sonstiger Mitarbeiter'), ('langjaehrig', 'Langjaehriger Mitarbeiter'), ('lehrer', 'Lehrer/in'), ('la_student', 'Lehramts-Student/in'), ('extern', 'Externe Person')], max_length=30)),
                ('is_external', models.BooleanField(default=False)),
                ('years_of_service', models.PositiveIntegerField(default=0)),
                ('first_start_date', models.DateField(blank=True, null=True)),
                ('freibetrag_used_elsewhere', models.BooleanField(default=False)),
                ('freibetrag_amount_elsewhere', models.DecimalField(decimal_places=2, default=0, max_digits=8)),
                ('freibetrag_verein_name', models.CharField(blank=True, default='', max_length=200)),
                ('onboarding_status', models.CharField(choices=[('registered', 'Registriert'), ('documents_pending', 'Dokumente ausstehend'), ('documents_complete', 'Dokumente vollstaendig'), ('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('archived', 'Archiviert')], default='registered', max_length=30)),
                ('notes', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='betreuer_profile', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Betreuer-Profil',
                'verbose_name_plural': 'Betreuer-Profile',
                'ordering': ['user__last_name', 'user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='RegistrationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('token', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('is_single_use', models.BooleanField(default=True, help_text='If True, link becomes inactive after one use.')),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('used_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.CharField(blank=True, default='', max_length=500)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_registration_links', to=settings.AUTH_USER_MODEL)),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registration_links', to='schools.school')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_registration_link', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Registrierungslink',
                'verbose_name_plural': 'Registrierungslinks',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('contract_number', models.CharField(max_length=50, unique=True)),
                ('custom_rate_60', models.DecimalField(blank=True, decimal_places=2, help_text='Optional custom rate for 60 min (overrides hourly_rate).', max_digits=6, null=True)),
                ('custom_rate_45', models.DecimalField(blank=True, decimal_places=2, help_text='Optional custom rate for 45 min (overrides hourly_rate).', max_digits=6, null=True)),
                ('hour_duration', models.PositiveIntegerField(choices=[(60, '60 Minuten'), (45, '45 Minuten')], default=60)),
                ('ag_name', models.CharField(blank=True, default='', help_text='Name of the AG (only for activity_type=ag).', max_length=200)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('generated', 'Generiert'), ('sent', 'Versendet'), ('signed', 'Unterschrieben'), ('active', 'Aktiv'), ('expired', 'Abgelaufen'), ('cancelled', 'Storniert')], default='draft', max_length=30)),
                ('signed_by_verein', models.BooleanField(default=False)),
                ('signed_by_betreuer', models.BooleanField(default=False)),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True, default='')),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rates.activitytype')),
                ('betreuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='contracts.betreuerprofile')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_contracts', to=settings.AUTH_USER_MODEL)),
                ('foerderprogramm', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contracts', to='schools.foerderprogramm')),
                ('hourly_rate', models.ForeignKey(help_text='Snapshot of the hourly rate at contract creation.', on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='rates.hourlyrate')),
                ('school', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='schools.school')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contracts', to='schools.schoolyear')),
            ],
            options={
                'verbose_name': 'Vertrag',
                'verbose_name_plural': 'Vertraege',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['betreuer', 'school_year'], name='contracts_c_betreue_0ca456_idx'), models.Index(fields=['school', 'school_year'], name='contracts_c_school__4b6da2_idx'), models.Index(fields=['status'], name='contracts_c_status_aa7a80_idx')],
            },
        ),
    ]
