# Generated by Django 5.1 on 2026-02-24 21:38

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='betreuerprofile',
            name='kreditorennummer',
            field=models.CharField(blank=True, default='', help_text='5-stellige Kreditorennummer fuer Buchhaltung.', max_length=5, validators=[django.core.validators.RegexValidator(message='Kreditorennummer muss genau 5 Ziffern sein.', regex='^\\d{5}$')]),
        ),
        migrations.AddField(
            model_name='betreuerprofile',
            name='projektnummer',
            field=models.CharField(blank=True, default='', help_text='8-stellige Projektnummer fuer DMS/Buchhaltung.', max_length=8, validators=[django.core.validators.RegexValidator(message='Projektnummer muss genau 8 Ziffern sein.', regex='^\\d{8}$')]),
        ),
    ]
