# Generated by Django 5.1 on 2026-03-03 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0003_contract_foerderprogramme_m2m'),
    ]

    operations = [
        migrations.AddField(
            model_name='betreuerprofile',
            name='unique_hash',
            field=models.CharField(blank=True, help_text='SHA256 hash of first_name + last_name + geburtsdatum for duplicate detection.', max_length=64, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='betreuerprofile',
            name='iban',
            field=models.CharField(blank=True, default='', max_length=34),
        ),
        migrations.AlterField(
            model_name='betreuerprofile',
            name='onboarding_status',
            field=models.CharField(choices=[('registered', 'Registriert'), ('pending_approval', 'Warte auf Genehmigung'), ('approved', 'Genehmigt'), ('documents_pending', 'Dokumente ausstehend'), ('documents_complete', 'Dokumente vollstaendig'), ('active', 'Aktiv'), ('inactive', 'Inaktiv'), ('archived', 'Archiviert')], default='registered', max_length=30),
        ),
        migrations.AlterField(
            model_name='contract',
            name='start_date',
            field=models.DateField(blank=True, help_text='Set by Koordinator during approval. Null until approved.', null=True),
        ),
    ]
