# Generated by Django 5.1 on 2026-07-01 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contracts', '0008_add_contract_indexes'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='betreuerprofile',
            new_name='contracts_b_onboard_e465a2_idx',
            old_name='contracts_b_onboard_idx',
        ),
        migrations.RenameIndex(
            model_name='betreuerprofile',
            new_name='contracts_b_unique__089a70_idx',
            old_name='contracts_b_hash_idx',
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='recipient_name',
            field=models.CharField(blank=True, default='', help_text='Name der eingeladenen Person (fuer die Anrede in der Mail).', max_length=200),
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='registrationlink',
            name='sent_to',
            field=models.EmailField(blank=True, default='', help_text='E-Mail-Adresse, an die die Einladung verschickt wurde.', max_length=254),
        ),
    ]
