# Generated by Django 5.1 on 2026-02-24 19:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActivityType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_active', models.BooleanField(default=True)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Taetigkeitsart',
                'verbose_name_plural': 'Taetigkeitsarten',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='HourlyRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('betreuer_type', models.CharField(choices=[('schueler', 'Schueler/in'), ('sonst_mitarbeiter', 'Sonstiger Mitarbeiter'), ('langjaehrig', 'Langjaehriger Mitarbeiter'), ('lehrer', 'Lehrer/in'), ('la_student', 'Lehramts-Student/in'), ('extern', 'Externe Person')], max_length=20)),
                ('rate_60min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('rate_45min', models.DecimalField(decimal_places=2, max_digits=6)),
                ('valid_from', models.DateField()),
                ('valid_until', models.DateField(blank=True, null=True)),
                ('activity_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rates', to='rates.activitytype')),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hourly_rates', to='schools.schoolyear')),
            ],
            options={
                'verbose_name': 'Stundensatz',
                'verbose_name_plural': 'Stundensaetze',
                'ordering': ['activity_type__sort_order', 'betreuer_type'],
                'constraints': [models.UniqueConstraint(fields=('activity_type', 'betreuer_type', 'valid_from'), name='unique_rate_per_type_and_date')],
            },
        ),
    ]
