# Generated by Django 5.1 on 2026-03-03 15:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('schools', '0004_foerderprogramm_budget'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Uebungsleiterpauschale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kalenderjahr', models.PositiveIntegerField(help_text='Kalenderjahr, fuer das die Pauschale gilt (z.B. 2026).', unique=True)),
                ('betrag', models.DecimalField(decimal_places=2, help_text='Jaehrlicher Freibetrag in EUR.', max_digits=10)),
                ('gesetzliche_grundlage', models.CharField(default='§3 Nr. 26 EStG', help_text='Gesetzliche Grundlage fuer die Pauschale.', max_length=100)),
                ('gueltig_ab', models.DateField(blank=True, help_text='Datum, ab dem dieser Betrag gilt (optional).', null=True)),
            ],
            options={
                'verbose_name': 'Uebungsleiterpauschale',
                'verbose_name_plural': 'Uebungsleiterpauschalen',
                'ordering': ['-kalenderjahr'],
            },
        ),
        migrations.CreateModel(
            name='ManuelleKostenbuchung',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('betrag', models.DecimalField(decimal_places=2, help_text='Betrag in EUR.', max_digits=10)),
                ('beschreibung', models.TextField(help_text='Beschreibung der Kostenbuchung.')),
                ('kategorie', models.CharField(choices=[('material', 'Material'), ('fortbildung', 'Fortbildung'), ('versicherung', 'Versicherung'), ('sonstiges', 'Sonstiges')], help_text='Kategorie der Kosten.', max_length=30)),
                ('beleg_nr', models.CharField(blank=True, default='', help_text='Optionale Belegnummer.', max_length=50)),
                ('datum', models.DateField(help_text='Datum der Kostenbuchung.')),
                ('erstellt_von', models.ForeignKey(blank=True, help_text='Benutzer, der die Buchung erstellt hat.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='erstellte_kostenbuchungen', to=settings.AUTH_USER_MODEL)),
                ('foerderprogramm', models.ForeignKey(help_text='Foerderprogramm, dem diese Kosten zugeordnet werden.', on_delete=django.db.models.deletion.CASCADE, related_name='manuelle_kostenbuchungen', to='schools.foerderprogramm')),
            ],
            options={
                'verbose_name': 'Manuelle Kostenbuchung',
                'verbose_name_plural': 'Manuelle Kostenbuchungen',
                'ordering': ['-datum'],
            },
        ),
    ]
