# Generated by Django 5.1 on 2026-02-24 20:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentRequirement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('description', models.TextField(blank=True, default='')),
                ('is_generated', models.BooleanField(default=False, help_text='System generates this document as PDF.')),
                ('is_required_internal', models.BooleanField(default=True, help_text='Required for internal betreuer (non-external).')),
                ('is_required_external', models.BooleanField(default=True, help_text='Required for external betreuer.')),
                ('renewal_interval_months', models.PositiveIntegerField(blank=True, help_text='Renewal interval in months (e.g. 24 for IfSB). NULL = no renewal.', null=True)),
                ('template_name', models.CharField(blank=True, default='', help_text='Django template path for PDF generation.', max_length=200)),
                ('sort_order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'verbose_name': 'Dokumentanforderung',
                'verbose_name_plural': 'Dokumentanforderungen',
                'ordering': ['sort_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('generated_file', models.FileField(blank=True, upload_to='documents/generated/%Y/%m/')),
                ('generated_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_file', models.FileField(blank=True, upload_to='documents/uploads/%Y/%m/')),
                ('uploaded_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('pending', 'Ausstehend'), ('generated', 'Generiert'), ('sent', 'Versendet'), ('uploaded', 'Hochgeladen'), ('verified', 'Verifiziert'), ('rejected', 'Abgelehnt')], default='pending', max_length=30)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('expires_at', models.DateField(blank=True, null=True)),
                ('renewal_reminder_sent', models.BooleanField(default=False)),
                ('notes', models.TextField(blank=True, default='')),
                ('betreuer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.betreuerprofile')),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='contracts.contract')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_documents', to=settings.AUTH_USER_MODEL)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='documents.documentrequirement')),
            ],
            options={
                'verbose_name': 'Dokument',
                'verbose_name_plural': 'Dokumente',
                'ordering': ['requirement__sort_order'],
                'constraints': [models.UniqueConstraint(fields=('contract', 'requirement'), name='unique_document_per_contract_requirement')],
            },
        ),
    ]
