# Generated by Django 5.1 on 2026-07-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_add_document_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentrequirement',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Inaktive Anforderungen erzeugen bei neuen Registrierungen keine Pflicht-Dokumente mehr (bestehende bleiben unveraendert).'),
        ),
    ]
