# Generated by Django 5.1 on 2026-02-24 21:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contracts', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyTimesheet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('month', models.PositiveIntegerField(help_text='1-12')),
                ('year', models.PositiveIntegerField()),
                ('status', models.CharField(choices=[('draft', 'Entwurf'), ('submitted', 'Eingereicht'), ('approved', 'Genehmigt'), ('rejected', 'Abgelehnt')], default='draft', max_length=20)),
                ('total_hours', models.DecimalField(decimal_places=2, default=0, help_text='Total hours (calculated from entries).', max_digits=6)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0, help_text='Total amount in EUR (hours x rate).', max_digits=8)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, default='')),
                ('notes', models.TextField(blank=True, default='')),
                ('approved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='approved_timesheets', to=settings.AUTH_USER_MODEL)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='timesheets', to='contracts.contract')),
            ],
            options={
                'verbose_name': 'Monatsnachweis',
                'verbose_name_plural': 'Monatsnachweise',
                'ordering': ['-year', '-month'],
            },
        ),
        migrations.CreateModel(
            name='TimeEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('break_minutes', models.PositiveIntegerField(default=0, help_text='Break duration in minutes.')),
                ('duration_minutes', models.PositiveIntegerField(default=0, editable=False, help_text='Auto-calculated: (end - start) - break.')),
                ('description', models.CharField(blank=True, default='', max_length=500)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='time_entries', to='contracts.contract')),
                ('timesheet', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entries', to='timetracking.monthlytimesheet')),
            ],
            options={
                'verbose_name': 'Stundeneintrag',
                'verbose_name_plural': 'Stundeneintraege',
                'ordering': ['-date', '-start_time'],
            },
        ),
        migrations.AddConstraint(
            model_name='monthlytimesheet',
            constraint=models.UniqueConstraint(fields=('contract', 'month', 'year'), name='unique_timesheet_per_contract_month'),
        ),
        migrations.AddIndex(
            model_name='timeentry',
            index=models.Index(fields=['contract', 'date'], name='timetrackin_contrac_2fc552_idx'),
        ),
    ]
