# Generated by Django 5.1 on 2026-02-24 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlytimesheet',
            name='generated_pdf',
            field=models.FileField(blank=True, default='', help_text='Auto-generated accounting PDF after approval.', upload_to='timesheets/pdf/%Y/%m/'),
        ),
    ]
