# Generated by Django 5.1 on 2026-07-02 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timetracking', '0005_add_timesheet_contract_status_idx'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='monthlytimesheet',
            new_name='timetrackin_status_52744e_idx',
            old_name='timetracking_mt_status_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlytimesheet',
            new_name='timetrackin_year_9f70dd_idx',
            old_name='timetracking_mt_ym_idx',
        ),
        migrations.RenameIndex(
            model_name='monthlytimesheet',
            new_name='timetrackin_status_0bba8b_idx',
            old_name='timetracking_mt_sym_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='timetrackin_date_7d698b_idx',
            old_name='timetracking_te_date_idx',
        ),
        migrations.RenameIndex(
            model_name='timeentry',
            new_name='timetrackin_foerder_0d5e80_idx',
            old_name='timetracking_te_fp_ts_idx',
        ),
    ]
