# Generated by Django 5.1 on 2026-02-24 19:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SchoolYear',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('is_current', models.BooleanField(default=False)),
                ('freibetrag_limit', models.DecimalField(decimal_places=2, default=3300.0, help_text='Jaehrlicher Freibetrag in EUR', max_digits=10)),
            ],
            options={
                'verbose_name': 'Schuljahr',
                'verbose_name_plural': 'Schuljahre',
                'ordering': ['-start_date'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=10, unique=True)),
                ('school_number', models.CharField(max_length=10, unique=True)),
                ('name', models.CharField(max_length=200)),
                ('short_name', models.CharField(blank=True, default='', max_length=50)),
                ('address', models.TextField(blank=True, default='')),
                ('school_type', models.CharField(choices=[('grundschule', 'Grundschule'), ('gesamtschule', 'Gesamtschule'), ('gymnasium', 'Gymnasium'), ('berufskolleg', 'Berufskolleg')], max_length=20)),
                ('is_ganztag', models.BooleanField(default=False)),
                ('schueler_count_sek1', models.PositiveIntegerField(default=0, help_text='Schueleranzahl Sek I')),
                ('primary_color', models.CharField(default='#575756', max_length=7)),
                ('is_active', models.BooleanField(default=True)),
                ('koordinator', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='koordinierte_schulen', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Schule',
                'verbose_name_plural': 'Schulen',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='Foerderprogramm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
                ('code', models.CharField(max_length=30, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('school_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='foerderprogramme', to='schools.schoolyear')),
            ],
            options={
                'verbose_name': 'Foerderprogramm',
                'verbose_name_plural': 'Foerderprogramme',
                'ordering': ['name'],
            },
        ),
    ]
