# Generated by Django 5.1 on 2026-07-01 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0003_processed_webhook_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=50)),
                ('status', models.CharField(choices=[('success', 'Erfolgreich gesendet'), ('failed', 'Fehlgeschlagen'), ('skipped', 'Uebersprungen (kein aktiver Endpoint)')], db_index=True, max_length=10)),
                ('endpoint_url', models.URLField(blank=True, default='', max_length=500)),
                ('http_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('payload', models.JSONField(blank=True, default=dict)),
                ('error', models.TextField(blank=True, default='')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Benachrichtigungs-Log',
                'verbose_name_plural': 'Benachrichtigungs-Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['event_type', 'created_at'], name='notificatio_event_t_988cb5_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_68c9bc_idx')],
            },
        ),
    ]
