# Generated by Django 5.1 on 2026-07-01 13:44

import apps.core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0004_notificationlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SmtpConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, default='', max_length=255)),
                ('port', models.PositiveIntegerField(default=587)),
                ('use_tls', models.BooleanField(default=True, help_text='STARTTLS (Standard, Port 587). Bei Port 465 stattdessen SSL nutzen.')),
                ('use_ssl', models.BooleanField(default=False, help_text='Implizites SSL (Port 465). NICHT gleichzeitig mit TLS aktivieren.')),
                ('username', models.CharField(blank=True, default='', max_length=255)),
                ('password', apps.core.models.EncryptedCharField(blank=True, default=None, help_text='SMTP-Passwort. Wird verschluesselt gespeichert.', max_length=255, null=True)),
                ('from_email', models.EmailField(blank=True, default='', help_text='Absenderadresse, z.B. noreply@fes-credo.de.', max_length=254)),
                ('from_name', models.CharField(blank=True, default='BetreuerApp CSFV', help_text='Angezeigter Absendername.', max_length=100)),
                ('admin_email', models.EmailField(blank=True, default='', help_text='Empfaenger fuer interne Benachrichtigungen (Duplikat, E-Mail-Abweichung, abgelaufenes Dokument, Freibetrag-Warnung).', max_length=254)),
                ('buchhaltung_email', models.EmailField(blank=True, default='', help_text='Empfaenger fuer Abrechnungs-Mails (genehmigter Stundennachweis).', max_length=254)),
                ('is_active', models.BooleanField(default=False, help_text='Erst aktivieren, wenn Host/User/Passwort korrekt gesetzt sind. Inaktiv = Versand faellt auf die .env-SMTP-Einstellungen zurueck.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'SMTP-Konfiguration',
                'verbose_name_plural': 'SMTP-Konfiguration',
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient', models.EmailField(max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=255)),
                ('kind', models.CharField(blank=True, db_index=True, default='', help_text='z.B. registration_invite, password_setup.', max_length=50)),
                ('status', models.CharField(choices=[('sent', 'Gesendet'), ('failed', 'Fehlgeschlagen'), ('skipped', 'Uebersprungen')], db_index=True, max_length=10)),
                ('detail', models.TextField(blank=True, default='', help_text='Message-ID bei Erfolg bzw. Fehlertext.')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'E-Mail-Log',
                'verbose_name_plural': 'E-Mail-Logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['kind', 'created_at'], name='notificatio_kind_d8ae76_idx'), models.Index(fields=['status', 'created_at'], name='notificatio_status_6192b4_idx')],
            },
        ),
    ]
