# Generated by Django 5.1 on 2026-07-03 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0005_smtpconfig_emaillog'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(choices=[('registration_invite', 'Einladung zur Registrierung (an neuen Betreuer)'), ('password_reset', 'Passwort zuruecksetzen (Self-Service)'), ('pending_approval', 'Neue Registrierung wartet auf Genehmigung (an Koordinator)'), ('betreuer_approved', 'Freigegeben - Passwort festlegen (an Betreuer)'), ('contract_created', 'Vertragsentwurf angelegt (an Betreuer)'), ('duplicate_detected', 'Moegliches Duplikat bei Registrierung (an Admin)'), ('email_mismatch', 'E-Mail-Abweichung bei Wiederholung (an Admin)'), ('document_expiring', 'Dokument laeuft bald ab (an Betreuer)'), ('document_expired', 'Dokument abgelaufen (an Admin)'), ('freibetrag_warning', 'Freibetrag-Warnung (an Admin)'), ('timesheet_approved', 'Stundennachweis genehmigt (an Buchhaltung)')], help_text='Mail-Typ. Pro Typ genau eine Vorlage.', max_length=50, unique=True)),
                ('subject', models.CharField(help_text='Betreff (Platzhalter erlaubt).', max_length=255)),
                ('body', models.TextField(help_text='Text der Mail. Leerzeile = neuer Absatz. Platzhalter wie {{name}}.')),
                ('cta_label', models.CharField(blank=True, default='', help_text='Beschriftung des Buttons (leer = kein Button). Das Link-Ziel wird vom System gesetzt.', max_length=100)),
                ('is_active', models.BooleanField(default=True, help_text='Inaktiv = es gilt wieder der eingebaute Standardtext.')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'E-Mail-Vorlage',
                'verbose_name_plural': 'E-Mail-Vorlagen',
                'ordering': ['key'],
            },
        ),
    ]
